import type { Category, Product, AddOn, MenuData } from './types';

export const categories: Category[] = [
  {
    id: 'doener',
    slug: 'doener',
    order: 1,
    icon: '🥙',
    name: { de: 'Döner', en: 'Döner', tr: 'Döner', ru: 'Дёнер' },
    tagline: {
      de: 'Frisch vom Drehspieß, im warmen Fladenbrot.',
      en: 'Fresh off the spit, in warm flatbread.',
      tr: 'Sıcak ekmekte taze döner.',
      ru: 'Свежий с вертела, в тёплой лепёшке.',
    },
  },
  {
    id: 'duerum',
    slug: 'duerum',
    order: 2,
    icon: '🌯',
    name: { de: 'Dürüm', en: 'Dürüm', tr: 'Dürüm', ru: 'Дюрюм' },
    tagline: {
      de: 'Im dünnen Yufka-Teig gerollt.',
      en: 'Rolled in thin yufka flatbread.',
      tr: 'İnce yufka içinde sarılı.',
      ru: 'Завернуто в тонкий лаваш юфка.',
    },
  },
  {
    id: 'lahmacun',
    slug: 'lahmacun',
    order: 3,
    icon: '🫓',
    name: { de: 'Lahmacun', en: 'Lahmacun', tr: 'Lahmacun', ru: 'Лахмаджун' },
    tagline: {
      de: 'Hauchdünn, im Steinofen gebacken.',
      en: 'Thin crust, baked in stone oven.',
      tr: 'İncecik hamur, taş fırında pişer.',
      ru: 'Тонкое тесто, выпекается в каменной печи.',
    },
  },
  {
    id: 'pide',
    slug: 'pide',
    order: 4,
    icon: '🛶',
    name: { de: 'Pide', en: 'Pide', tr: 'Pide', ru: 'Пиде' },
    tagline: {
      de: 'Traditionelle türkische Pide.',
      en: 'Traditional Turkish pide.',
      tr: 'Geleneksel Türk pidesi.',
      ru: 'Традиционная турецкая пиде.',
    },
  },
  {
    id: 'pizza',
    slug: 'pizza',
    order: 5,
    icon: '🍕',
    name: { de: 'Pizza', en: 'Pizza', tr: 'Pizza', ru: 'Пицца' },
    tagline: {
      de: 'Ø 32 cm, knuspriger Boden.',
      en: '32 cm diameter, crispy base.',
      tr: '32 cm, çıtır hamur.',
      ru: '32 см, хрустящее тесто.',
    },
  },
  {
    id: 'burger',
    slug: 'burger',
    order: 6,
    icon: '🍔',
    name: { de: 'Burger', en: 'Burgers', tr: 'Burger', ru: 'Бургеры' },
    tagline: {
      de: 'Hausgemachte Patties, frische Buns.',
      en: 'Homemade patties, fresh buns.',
      tr: 'Ev yapımı köfte, taze ekmek.',
      ru: 'Домашние котлеты, свежие булочки.',
    },
  },
  {
    id: 'beilagen',
    slug: 'beilagen',
    order: 7,
    icon: '🍟',
    name: { de: 'Beilagen', en: 'Sides', tr: 'Yanlar', ru: 'Закуски' },
    tagline: {
      de: 'Pommes, Wings & mehr.',
      en: 'Fries, wings & more.',
      tr: 'Patates, kanat ve daha fazlası.',
      ru: 'Картофель, крылья и многое другое.',
    },
  },
  {
    id: 'salate',
    slug: 'salate',
    order: 8,
    icon: '🥗',
    name: { de: 'Salate', en: 'Salads', tr: 'Salatalar', ru: 'Салаты' },
    tagline: {
      de: 'Frisch, leicht, knackig.',
      en: 'Fresh, light, crisp.',
      tr: 'Taze, hafif, çıtır.',
      ru: 'Свежие, лёгкие, хрустящие.',
    },
  },
  {
    id: 'suesses',
    slug: 'suesses',
    order: 9,
    icon: '🍰',
    name: { de: 'Süßes', en: 'Desserts', tr: 'Tatlılar', ru: 'Десерты' },
    tagline: {
      de: 'Türkische Süßspeisen.',
      en: 'Turkish sweets.',
      tr: 'Türk tatlıları.',
      ru: 'Турецкие сладости.',
    },
  },
  {
    id: 'getraenke',
    slug: 'getraenke',
    order: 10,
    icon: '🥤',
    name: { de: 'Getränke', en: 'Drinks', tr: 'İçecekler', ru: 'Напитки' },
    tagline: {
      de: 'Kalt serviert.',
      en: 'Served chilled.',
      tr: 'Soğuk servis.',
      ru: 'Подаются охлаждёнными.',
    },
  },
];

export const products: Product[] = [
  // ───── DÖNER ─────
  {
    id: 'doener-klassisch',
    categoryId: 'doener',
    priceCents: 750,
    popular: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Döner Klassisch',
      en: 'Classic Döner',
      tr: 'Klasik Döner',
      ru: 'Классический дёнер',
    },
    description: {
      de: 'Saftiges Kalbfleisch vom Spieß, frischer Salat, Tomate, Gurke, Zwiebel und hausgemachte Sauce.',
      en: 'Juicy veal from the spit, fresh salad, tomato, cucumber, onion and house sauce.',
      tr: 'Şişten taze dana eti, marul, domates, salatalık, soğan ve ev yapımı sos.',
      ru: 'Сочная телятина с вертела, свежий салат, помидор, огурец, лук и фирменный соус.',
    },
  },
  {
    id: 'doener-kaese',
    categoryId: 'doener',
    priceCents: 800,
    allergens: ['A', 'G'],
    name: {
      de: 'Döner mit Käse',
      en: 'Döner with Cheese',
      tr: 'Peynirli Döner',
      ru: 'Дёнер с сыром',
    },
    description: {
      de: 'Klassisch verfeinert mit geschmolzenem Gouda.',
      en: 'Classic refined with melted Gouda.',
      tr: 'Eriyik Gouda peyniri ile zenginleştirilmiş klasik.',
      ru: 'Классический с плавленым Гаудой.',
    },
  },
  {
    id: 'doener-scharf',
    categoryId: 'doener',
    priceCents: 750,
    spicy: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Döner Scharf',
      en: 'Spicy Döner',
      tr: 'Acılı Döner',
      ru: 'Острый дёнер',
    },
    description: {
      de: 'Mit feuriger Chili-Sauce für echte Liebhaber.',
      en: 'With fiery chili sauce for true fans.',
      tr: 'Gerçek severler için ateşli biber sosu ile.',
      ru: 'С огненным чили-соусом для настоящих любителей.',
    },
  },
  {
    id: 'doener-haehnchen',
    categoryId: 'doener',
    priceCents: 750,
    allergens: ['A', 'G'],
    name: {
      de: 'Hähnchen Döner',
      en: 'Chicken Döner',
      tr: 'Tavuk Döner',
      ru: 'Куриный дёнер',
    },
    description: {
      de: 'Zartes Hähnchenfleisch, mariniert in unserer Geheim-Gewürzmischung.',
      en: 'Tender chicken marinated in our secret spice blend.',
      tr: 'Özel baharat karışımımızla marine edilmiş yumuşak tavuk eti.',
      ru: 'Нежная курица, маринованная в нашей секретной смеси специй.',
    },
  },
  {
    id: 'doener-falafel',
    categoryId: 'doener',
    priceCents: 700,
    vegetarian: true,
    vegan: true,
    allergens: ['A'],
    name: {
      de: 'Falafel Döner',
      en: 'Falafel Döner',
      tr: 'Falafel Döner',
      ru: 'Дёнер с фалафелем',
    },
    description: {
      de: 'Knusprige Kichererbsenbällchen mit Tahini-Sauce.',
      en: 'Crispy chickpea balls with tahini sauce.',
      tr: 'Tahin sosu ile çıtır nohut topları.',
      ru: 'Хрустящие шарики из нута с соусом тахини.',
    },
  },

  // ───── DÜRÜM ─────
  {
    id: 'duerum-klassisch',
    categoryId: 'duerum',
    priceCents: 850,
    popular: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Dürüm Klassisch',
      en: 'Classic Dürüm',
      tr: 'Klasik Dürüm',
      ru: 'Классический дюрюм',
    },
    description: {
      de: 'Kalbfleisch im hauchdünnen Yufka-Brot mit allem Drum und Dran.',
      en: 'Veal in paper-thin yufka with all the trimmings.',
      tr: 'İncecik yufkada dana etiyle her şey dahil.',
      ru: 'Телятина в тончайшем лаваше юфка со всеми добавками.',
    },
  },
  {
    id: 'duerum-kaese',
    categoryId: 'duerum',
    priceCents: 900,
    allergens: ['A', 'G'],
    name: {
      de: 'Dürüm mit Käse',
      en: 'Dürüm with Cheese',
      tr: 'Peynirli Dürüm',
      ru: 'Дюрюм с сыром',
    },
    description: {
      de: 'Klassisch mit großzügig geschmolzenem Käse.',
      en: 'Classic with generously melted cheese.',
      tr: 'Bol erimiş peynirli klasik.',
      ru: 'Классический с щедрой порцией плавленого сыра.',
    },
  },
  {
    id: 'duerum-scharf',
    categoryId: 'duerum',
    priceCents: 850,
    spicy: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Dürüm Scharf',
      en: 'Spicy Dürüm',
      tr: 'Acılı Dürüm',
      ru: 'Острый дюрюм',
    },
    description: {
      de: 'Mit extra Chili & Peperoni.',
      en: 'With extra chili and peperoni.',
      tr: 'Ekstra biber ve acı biber ile.',
      ru: 'С добавлением чили и перца пепперони.',
    },
  },
  {
    id: 'duerum-haehnchen',
    categoryId: 'duerum',
    priceCents: 850,
    allergens: ['A', 'G'],
    name: {
      de: 'Hähnchen Dürüm',
      en: 'Chicken Dürüm',
      tr: 'Tavuk Dürüm',
      ru: 'Куриный дюрюм',
    },
    description: {
      de: 'Mariniertes Hähnchen, Salat, Saucen, im Yufka gerollt.',
      en: 'Marinated chicken, salad, sauces, rolled in yufka.',
      tr: 'Marine tavuk, marul, soslar, yufkada sarılı.',
      ru: 'Маринованная курица, салат, соусы, завёрнутые в юфку.',
    },
  },
  {
    id: 'duerum-falafel',
    categoryId: 'duerum',
    priceCents: 800,
    vegetarian: true,
    vegan: true,
    allergens: ['A'],
    name: {
      de: 'Falafel Dürüm',
      en: 'Falafel Dürüm',
      tr: 'Falafel Dürüm',
      ru: 'Дюрюм с фалафелем',
    },
    description: {
      de: 'Mit Falafel, Hummus und frischem Gemüse.',
      en: 'With falafel, hummus and fresh veggies.',
      tr: 'Falafel, humus ve taze sebzeli.',
      ru: 'С фалафелем, хумусом и свежими овощами.',
    },
  },

  // ───── LAHMACUN ─────
  {
    id: 'lahmacun-klassisch',
    categoryId: 'lahmacun',
    priceCents: 550,
    allergens: ['A'],
    name: {
      de: 'Lahmacun Klassisch',
      en: 'Classic Lahmacun',
      tr: 'Klasik Lahmacun',
      ru: 'Классический лахмаджун',
    },
    description: {
      de: 'Hauchdünner Teig belegt mit feinem Hackfleisch, Petersilie und Gewürzen.',
      en: 'Paper-thin dough topped with fine minced meat, parsley and spices.',
      tr: 'İncecik hamur, ince kıyma, maydanoz ve baharat ile.',
      ru: 'Тонкое тесто с мелко рубленым мясом, петрушкой и специями.',
    },
  },
  {
    id: 'lahmacun-doener',
    categoryId: 'lahmacun',
    priceCents: 750,
    popular: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Lahmacun mit Döner',
      en: 'Lahmacun with Döner',
      tr: 'Dönerli Lahmacun',
      ru: 'Лахмаджун с дёнером',
    },
    description: {
      de: 'Lahmacun gerollt mit Dönerfleisch, Salat und Sauce.',
      en: 'Lahmacun rolled with döner meat, salad and sauce.',
      tr: 'Döner et, marul ve sos ile sarılmış lahmacun.',
      ru: 'Лахмаджун, свёрнутый с мясом дёнера, салатом и соусом.',
    },
  },
  {
    id: 'lahmacun-kaese',
    categoryId: 'lahmacun',
    priceCents: 650,
    allergens: ['A', 'G'],
    name: {
      de: 'Lahmacun mit Käse',
      en: 'Lahmacun with Cheese',
      tr: 'Peynirli Lahmacun',
      ru: 'Лахмаджун с сыром',
    },
    description: {
      de: 'Klassischer Lahmacun mit geschmolzenem Käse.',
      en: 'Classic lahmacun with melted cheese.',
      tr: 'Erimiş peynirli klasik lahmacun.',
      ru: 'Классический лахмаджун с плавленым сыром.',
    },
  },
  {
    id: 'lahmacun-vegetarisch',
    categoryId: 'lahmacun',
    priceCents: 600,
    vegetarian: true,
    allergens: ['A'],
    name: {
      de: 'Lahmacun Vegetarisch',
      en: 'Vegetarian Lahmacun',
      tr: 'Vejetaryen Lahmacun',
      ru: 'Вегетарианский лахмаджун',
    },
    description: {
      de: 'Mit gegrilltem Gemüse, Tomaten und Kräutern.',
      en: 'With grilled veggies, tomatoes and herbs.',
      tr: 'Izgara sebze, domates ve otlar ile.',
      ru: 'С овощами гриль, помидорами и зеленью.',
    },
  },

  // ───── PIDE ─────
  {
    id: 'pide-kaese',
    categoryId: 'pide',
    priceCents: 1100,
    vegetarian: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Käse Pide',
      en: 'Cheese Pide',
      tr: 'Peynirli Pide',
      ru: 'Пиде с сыром',
    },
    description: {
      de: 'Pide mit reichlich Mozzarella und Schafskäse.',
      en: 'Pide with plenty of mozzarella and feta.',
      tr: 'Bol mozzarella ve beyaz peynirli pide.',
      ru: 'Пиде с большим количеством моцареллы и брынзы.',
    },
  },
  {
    id: 'pide-sucuk',
    categoryId: 'pide',
    priceCents: 1250,
    allergens: ['A', 'G'],
    name: {
      de: 'Sucuk Pide',
      en: 'Sucuk Pide',
      tr: 'Sucuklu Pide',
      ru: 'Пиде с суджуком',
    },
    description: {
      de: 'Mit türkischer Knoblauchwurst und Mozzarella.',
      en: 'With Turkish garlic sausage and mozzarella.',
      tr: 'Türk sarımsaklı sucuk ve mozzarella ile.',
      ru: 'С турецкой чесночной колбасой и моцареллой.',
    },
  },
  {
    id: 'pide-hackfleisch',
    categoryId: 'pide',
    priceCents: 1300,
    popular: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Hackfleisch Pide',
      en: 'Minced Meat Pide',
      tr: 'Kıymalı Pide',
      ru: 'Пиде с фаршем',
    },
    description: {
      de: 'Würziges Hackfleisch, Zwiebeln, Paprika.',
      en: 'Spiced minced meat, onions, bell pepper.',
      tr: 'Baharatlı kıyma, soğan, biber.',
      ru: 'Острый фарш, лук, болгарский перец.',
    },
  },
  {
    id: 'pide-spinat',
    categoryId: 'pide',
    priceCents: 1150,
    vegetarian: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Spinat-Käse Pide',
      en: 'Spinach-Cheese Pide',
      tr: 'Ispanaklı Peynirli Pide',
      ru: 'Пиде со шпинатом и сыром',
    },
    description: {
      de: 'Frischer Spinat und Schafskäse.',
      en: 'Fresh spinach and feta cheese.',
      tr: 'Taze ıspanak ve beyaz peynir.',
      ru: 'Свежий шпинат и брынза.',
    },
  },
  {
    id: 'pide-mix',
    categoryId: 'pide',
    priceCents: 1350,
    allergens: ['A', 'G'],
    name: {
      de: 'Mix Pide',
      en: 'Mix Pide',
      tr: 'Karışık Pide',
      ru: 'Микс-пиде',
    },
    description: {
      de: 'Sucuk, Hackfleisch und Mozzarella vereint.',
      en: 'Sucuk, minced meat and mozzarella combined.',
      tr: 'Sucuk, kıyma ve mozzarella birlikte.',
      ru: 'Суджук, фарш и моцарелла вместе.',
    },
  },

  // ───── PIZZA ─────
  {
    id: 'pizza-margherita',
    categoryId: 'pizza',
    priceCents: 900,
    vegetarian: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Pizza Margherita',
      en: 'Pizza Margherita',
      tr: 'Margarita Pizza',
      ru: 'Пицца Маргарита',
    },
    description: {
      de: 'Tomaten, Mozzarella, frisches Basilikum.',
      en: 'Tomato, mozzarella, fresh basil.',
      tr: 'Domates, mozzarella, taze fesleğen.',
      ru: 'Томаты, моцарелла, свежий базилик.',
    },
  },
  {
    id: 'pizza-salami',
    categoryId: 'pizza',
    priceCents: 1050,
    popular: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Pizza Salami',
      en: 'Pizza Salami',
      tr: 'Salamlı Pizza',
      ru: 'Пицца Салями',
    },
    description: {
      de: 'Mit feiner italienischer Salami.',
      en: 'With fine Italian salami.',
      tr: 'İnce İtalyan salamı ile.',
      ru: 'С тонкой итальянской салями.',
    },
  },
  {
    id: 'pizza-tonno',
    categoryId: 'pizza',
    priceCents: 1100,
    allergens: ['A', 'D', 'G'],
    name: {
      de: 'Pizza Tonno',
      en: 'Pizza Tonno',
      tr: 'Ton Balıklı Pizza',
      ru: 'Пицца Тонно',
    },
    description: {
      de: 'Thunfisch und Zwiebeln auf Mozzarella.',
      en: 'Tuna and onions on mozzarella.',
      tr: 'Mozzarella üzerine ton balığı ve soğan.',
      ru: 'Тунец и лук на моцарелле.',
    },
  },
  {
    id: 'pizza-funghi',
    categoryId: 'pizza',
    priceCents: 1000,
    vegetarian: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Pizza Funghi',
      en: 'Pizza Funghi',
      tr: 'Mantarlı Pizza',
      ru: 'Пицца Фунги',
    },
    description: {
      de: 'Frische Champignons und Mozzarella.',
      en: 'Fresh mushrooms and mozzarella.',
      tr: 'Taze mantar ve mozzarella.',
      ru: 'Свежие шампиньоны и моцарелла.',
    },
  },
  {
    id: 'pizza-diavolo',
    categoryId: 'pizza',
    priceCents: 1150,
    spicy: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Pizza Diavolo',
      en: 'Pizza Diavolo',
      tr: 'Diavolo Pizza',
      ru: 'Пицца Дьяволо',
    },
    description: {
      de: 'Salami, scharfe Peperoni, Chili.',
      en: 'Salami, hot peperoni, chili.',
      tr: 'Salam, acı biber, chili.',
      ru: 'Салями, острые перцы, чили.',
    },
  },
  {
    id: 'pizza-vegetarisch',
    categoryId: 'pizza',
    priceCents: 1050,
    vegetarian: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Pizza Vegetarisch',
      en: 'Pizza Vegetarian',
      tr: 'Vejetaryen Pizza',
      ru: 'Вегетарианская пицца',
    },
    description: {
      de: 'Paprika, Champignons, Zwiebeln, Mais, Oliven.',
      en: 'Bell pepper, mushrooms, onions, corn, olives.',
      tr: 'Biber, mantar, soğan, mısır, zeytin.',
      ru: 'Перец, шампиньоны, лук, кукуруза, оливки.',
    },
  },

  // ───── BURGER ─────
  {
    id: 'burger-cheese',
    categoryId: 'burger',
    priceCents: 950,
    popular: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Classic Cheeseburger',
      en: 'Classic Cheeseburger',
      tr: 'Klasik Cheeseburger',
      ru: 'Классический чизбургер',
    },
    description: {
      de: '200 g Beef-Patty, Cheddar, Salat, Tomate, Burger-Sauce.',
      en: '200 g beef patty, cheddar, lettuce, tomato, burger sauce.',
      tr: '200 gr dana köfte, cheddar, marul, domates, burger sosu.',
      ru: 'Котлета 200 г, чеддер, салат, томат, бургер-соус.',
    },
  },
  {
    id: 'burger-double',
    categoryId: 'burger',
    priceCents: 1200,
    allergens: ['A', 'G'],
    name: {
      de: 'Double Cheese',
      en: 'Double Cheese',
      tr: 'Çift Peynirli',
      ru: 'Дабл чиз',
    },
    description: {
      de: 'Doppeltes Patty, doppelter Cheddar, doppelter Genuss.',
      en: 'Double patty, double cheddar, double pleasure.',
      tr: 'Çift köfte, çift cheddar, çift keyif.',
      ru: 'Двойная котлета, двойной чеддер, двойное удовольствие.',
    },
  },
  {
    id: 'burger-chicken',
    categoryId: 'burger',
    priceCents: 900,
    allergens: ['A', 'G'],
    name: {
      de: 'Chicken Crispy',
      en: 'Crispy Chicken',
      tr: 'Çıtır Tavuk',
      ru: 'Кранчи-чикен',
    },
    description: {
      de: 'Knuspriges Hähnchenfilet, Coleslaw, Honey-Mustard.',
      en: 'Crispy chicken fillet, coleslaw, honey mustard.',
      tr: 'Çıtır tavuk fileto, lahana salatası, ballı hardal.',
      ru: 'Хрустящее куриное филе, коул-слоу, медово-горчичный соус.',
    },
  },
  {
    id: 'burger-veggie',
    categoryId: 'burger',
    priceCents: 850,
    vegetarian: true,
    allergens: ['A', 'G'],
    name: {
      de: 'Veggie Burger',
      en: 'Veggie Burger',
      tr: 'Vejetaryen Burger',
      ru: 'Вегетарианский бургер',
    },
    description: {
      de: 'Hausgemachtes Gemüse-Patty, Avocado, Rucola.',
      en: 'House-made veggie patty, avocado, arugula.',
      tr: 'Ev yapımı sebze köfte, avokado, roka.',
      ru: 'Домашняя овощная котлета, авокадо, руккола.',
    },
  },

  // ───── BEILAGEN ─────
  {
    id: 'side-pommes',
    categoryId: 'beilagen',
    priceCents: 400,
    vegetarian: true,
    vegan: true,
    name: {
      de: 'Pommes Frites',
      en: 'French Fries',
      tr: 'Patates Kızartması',
      ru: 'Картофель фри',
    },
    description: {
      de: 'Knusprig goldgelb, mit Meersalz.',
      en: 'Golden crispy, with sea salt.',
      tr: 'Altın sarısı çıtır, deniz tuzlu.',
      ru: 'Золотистый хрустящий, с морской солью.',
    },
  },
  {
    id: 'side-pommes-kaese',
    categoryId: 'beilagen',
    priceCents: 500,
    vegetarian: true,
    allergens: ['G'],
    name: {
      de: 'Pommes mit Käse',
      en: 'Cheesy Fries',
      tr: 'Peynirli Patates',
      ru: 'Фри с сыром',
    },
    description: {
      de: 'Pommes mit geschmolzenem Cheddar.',
      en: 'Fries with melted cheddar.',
      tr: 'Eriyik cheddar peynirli patates.',
      ru: 'Картофель с плавленым чеддером.',
    },
  },
  {
    id: 'side-suess-pommes',
    categoryId: 'beilagen',
    priceCents: 550,
    vegetarian: true,
    vegan: true,
    name: {
      de: 'Süßkartoffel-Pommes',
      en: 'Sweet Potato Fries',
      tr: 'Tatlı Patates Kızartması',
      ru: 'Картофель из батата',
    },
    description: {
      de: 'Süßlich-würzig, mit Paprika.',
      en: 'Sweet and savory, with paprika.',
      tr: 'Tatlı-baharatlı, paprika ile.',
      ru: 'Сладко-пряный, с паприкой.',
    },
  },
  {
    id: 'side-onion-rings',
    categoryId: 'beilagen',
    priceCents: 450,
    vegetarian: true,
    allergens: ['A'],
    name: {
      de: 'Onion Rings',
      en: 'Onion Rings',
      tr: 'Soğan Halkası',
      ru: 'Луковые кольца',
    },
    description: {
      de: 'Im Bierteig frittiert.',
      en: 'Beer-battered.',
      tr: 'Bira hamurunda kızartılmış.',
      ru: 'В пивном кляре.',
    },
  },
  {
    id: 'side-wings',
    categoryId: 'beilagen',
    priceCents: 650,
    name: {
      de: 'Chicken Wings (6 St.)',
      en: 'Chicken Wings (6 pcs)',
      tr: 'Tavuk Kanat (6 ad)',
      ru: 'Куриные крылья (6 шт)',
    },
    description: {
      de: 'Mariniert, scharf gegrillt, mit BBQ-Dip.',
      en: 'Marinated, grilled hot, with BBQ dip.',
      tr: 'Marine, ızgara, BBQ soslu.',
      ru: 'Маринованные, гриль, с соусом BBQ.',
    },
  },
  {
    id: 'side-falafel',
    categoryId: 'beilagen',
    priceCents: 550,
    vegetarian: true,
    vegan: true,
    name: {
      de: 'Falafel (6 St.)',
      en: 'Falafel (6 pcs)',
      tr: 'Falafel (6 ad)',
      ru: 'Фалафель (6 шт)',
    },
    description: {
      de: 'Knusprige Kichererbsenbällchen mit Tahini.',
      en: 'Crispy chickpea balls with tahini.',
      tr: 'Tahin ile çıtır nohut topları.',
      ru: 'Хрустящие шарики из нута с тахини.',
    },
  },

  // ───── SALATE ─────
  {
    id: 'salad-bauer',
    categoryId: 'salate',
    priceCents: 850,
    vegetarian: true,
    allergens: ['G'],
    name: {
      de: 'Bauernsalat',
      en: 'Farmer Salad',
      tr: 'Köylü Salata',
      ru: 'Крестьянский салат',
    },
    description: {
      de: 'Tomate, Gurke, Paprika, Zwiebel, Oliven, Feta.',
      en: 'Tomato, cucumber, pepper, onion, olives, feta.',
      tr: 'Domates, salatalık, biber, soğan, zeytin, beyaz peynir.',
      ru: 'Помидор, огурец, перец, лук, маслины, фета.',
    },
  },
  {
    id: 'salad-hirten',
    categoryId: 'salate',
    priceCents: 900,
    vegetarian: true,
    allergens: ['G'],
    name: {
      de: 'Hirtensalat',
      en: 'Shepherd Salad',
      tr: 'Çoban Salata',
      ru: 'Пастуший салат',
    },
    description: {
      de: 'Türkischer Klassiker mit reichlich Schafskäse.',
      en: 'Turkish classic with plenty of feta.',
      tr: 'Bol beyaz peynirli Türk klasiği.',
      ru: 'Турецкая классика с большим количеством брынзы.',
    },
  },
  {
    id: 'salad-caesar',
    categoryId: 'salate',
    priceCents: 1050,
    allergens: ['A', 'D', 'G'],
    name: {
      de: 'Caesar Salat mit Hähnchen',
      en: 'Caesar Salad with Chicken',
      tr: 'Tavuklu Sezar Salata',
      ru: 'Цезарь с курицей',
    },
    description: {
      de: 'Römersalat, Croutons, Parmesan, Caesar-Dressing.',
      en: 'Romaine, croutons, parmesan, Caesar dressing.',
      tr: 'Marul, kruton, parmesan, Sezar sos.',
      ru: 'Романо, крутоны, пармезан, соус Цезарь.',
    },
  },
  {
    id: 'salad-tonno',
    categoryId: 'salate',
    priceCents: 950,
    allergens: ['D', 'G'],
    name: {
      de: 'Tonno Salat',
      en: 'Tuna Salad',
      tr: 'Ton Balıklı Salata',
      ru: 'Салат с тунцом',
    },
    description: {
      de: 'Bunter Salat mit Thunfisch und Ei.',
      en: 'Colorful salad with tuna and egg.',
      tr: 'Ton balığı ve yumurtalı renkli salata.',
      ru: 'Разноцветный салат с тунцом и яйцом.',
    },
  },

  // ───── SÜSSES ─────
  {
    id: 'dessert-baklava',
    categoryId: 'suesses',
    priceCents: 550,
    vegetarian: true,
    allergens: ['A', 'G', 'H'],
    name: {
      de: 'Baklava (3 St.)',
      en: 'Baklava (3 pcs)',
      tr: 'Baklava (3 ad)',
      ru: 'Пахлава (3 шт)',
    },
    description: {
      de: 'Mit Pistazien und Honigsirup.',
      en: 'With pistachios and honey syrup.',
      tr: 'Antep fıstığı ve ballı şurup ile.',
      ru: 'С фисташками и медовым сиропом.',
    },
  },
  {
    id: 'dessert-kuenefe',
    categoryId: 'suesses',
    priceCents: 650,
    popular: true,
    vegetarian: true,
    allergens: ['A', 'G', 'H'],
    name: {
      de: 'Künefe',
      en: 'Künefe',
      tr: 'Künefe',
      ru: 'Кюнефе',
    },
    description: {
      de: 'Warmes Käsegebäck mit Sirup und Pistazien.',
      en: 'Warm cheese pastry with syrup and pistachios.',
      tr: 'Şerbet ve fıstıklı sıcak peynir tatlısı.',
      ru: 'Тёплая сырная выпечка с сиропом и фисташками.',
    },
  },
  {
    id: 'dessert-suetlac',
    categoryId: 'suesses',
    priceCents: 450,
    vegetarian: true,
    allergens: ['G'],
    name: {
      de: 'Sütlaç',
      en: 'Rice Pudding',
      tr: 'Sütlaç',
      ru: 'Сютлач',
    },
    description: {
      de: 'Türkischer Milchreis mit Zimt.',
      en: 'Turkish rice pudding with cinnamon.',
      tr: 'Tarçınlı sütlaç.',
      ru: 'Турецкий молочный рис с корицей.',
    },
  },
  {
    id: 'dessert-lava',
    categoryId: 'suesses',
    priceCents: 500,
    vegetarian: true,
    allergens: ['A', 'C', 'G'],
    name: {
      de: 'Schoko-Lava-Kuchen',
      en: 'Chocolate Lava Cake',
      tr: 'Çikolatalı Sufle',
      ru: 'Шоколадный фондан',
    },
    description: {
      de: 'Warm mit flüssigem Schokoladenkern.',
      en: 'Warm with molten chocolate center.',
      tr: 'Sıcak, akışkan çikolatalı.',
      ru: 'Тёплый, с жидким шоколадным сердцем.',
    },
  },

  // ───── GETRÄNKE ─────
  {
    id: 'drink-cola',
    categoryId: 'getraenke',
    priceCents: 250,
    vegetarian: true,
    name: {
      de: 'Coca-Cola 0,5 L',
      en: 'Coca-Cola 0.5 L',
      tr: 'Coca-Cola 0,5 L',
      ru: 'Coca-Cola 0,5 л',
    },
    description: { de: 'Eiskalt.', en: 'Ice cold.', tr: 'Buz gibi.', ru: 'Ледяная.' },
  },
  {
    id: 'drink-fanta',
    categoryId: 'getraenke',
    priceCents: 250,
    vegetarian: true,
    name: {
      de: 'Fanta 0,5 L',
      en: 'Fanta 0.5 L',
      tr: 'Fanta 0,5 L',
      ru: 'Fanta 0,5 л',
    },
    description: { de: 'Eiskalt.', en: 'Ice cold.', tr: 'Buz gibi.', ru: 'Ледяная.' },
  },
  {
    id: 'drink-sprite',
    categoryId: 'getraenke',
    priceCents: 250,
    vegetarian: true,
    name: {
      de: 'Sprite 0,5 L',
      en: 'Sprite 0.5 L',
      tr: 'Sprite 0,5 L',
      ru: 'Sprite 0,5 л',
    },
    description: { de: 'Eiskalt.', en: 'Ice cold.', tr: 'Buz gibi.', ru: 'Ледяная.' },
  },
  {
    id: 'drink-ayran',
    categoryId: 'getraenke',
    priceCents: 180,
    vegetarian: true,
    allergens: ['G'],
    name: {
      de: 'Ayran 0,25 L',
      en: 'Ayran 0.25 L',
      tr: 'Ayran 0,25 L',
      ru: 'Айран 0,25 л',
    },
    description: {
      de: 'Türkisches Joghurtgetränk.',
      en: 'Turkish yogurt drink.',
      tr: 'Türk yoğurt içeceği.',
      ru: 'Турецкий йогуртовый напиток.',
    },
  },
  {
    id: 'drink-wasser',
    categoryId: 'getraenke',
    priceCents: 180,
    vegan: true,
    name: {
      de: 'Wasser 0,5 L',
      en: 'Water 0.5 L',
      tr: 'Su 0,5 L',
      ru: 'Вода 0,5 л',
    },
    description: { de: 'Still / Sprudel.', en: 'Still / sparkling.', tr: 'Sade / gazlı.', ru: 'Без газа / с газом.' },
  },
  {
    id: 'drink-apfelschorle',
    categoryId: 'getraenke',
    priceCents: 250,
    vegan: true,
    name: {
      de: 'Apfelschorle 0,5 L',
      en: 'Apple Spritzer 0.5 L',
      tr: 'Elma Sodası 0,5 L',
      ru: 'Яблочный шпритц 0,5 л',
    },
    description: { de: 'Apfelsaft mit Mineralwasser.', en: 'Apple juice with sparkling water.', tr: 'Elma suyu ve mineral su.', ru: 'Яблочный сок с минералкой.' },
  },
  {
    id: 'drink-cay',
    categoryId: 'getraenke',
    priceCents: 200,
    vegan: true,
    name: {
      de: 'Türkischer Tee',
      en: 'Turkish Tea',
      tr: 'Çay',
      ru: 'Турецкий чай',
    },
    description: { de: 'Im Tulpenglas serviert.', en: 'Served in a tulip glass.', tr: 'İnce belli bardakta.', ru: 'Подаётся в стакане-тюльпане.' },
  },
  {
    id: 'drink-kahve',
    categoryId: 'getraenke',
    priceCents: 300,
    vegan: true,
    name: {
      de: 'Türkischer Kaffee',
      en: 'Turkish Coffee',
      tr: 'Türk Kahvesi',
      ru: 'Турецкий кофе',
    },
    description: {
      de: 'Traditionell zubereitet, mit Lokum.',
      en: 'Traditionally brewed, with lokum.',
      tr: 'Geleneksel, lokumla.',
      ru: 'Традиционно сваренный, с лукумом.',
    },
  },
];

export const addons: AddOn[] = [
  {
    id: 'extra-fleisch',
    priceCents: 250,
    name: { de: 'Extra Fleisch', en: 'Extra Meat', tr: 'Ekstra Et', ru: 'Доп. мясо' },
  },
  {
    id: 'extra-kaese',
    priceCents: 100,
    name: { de: 'Extra Käse', en: 'Extra Cheese', tr: 'Ekstra Peynir', ru: 'Доп. сыр' },
  },
  {
    id: 'extra-sauce',
    priceCents: 50,
    name: { de: 'Extra Sauce', en: 'Extra Sauce', tr: 'Ekstra Sos', ru: 'Доп. соус' },
  },
];

export const menu: MenuData = { categories, products, addons };

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function formatPrice(cents: number, locale: string = 'de'): string {
  const eur = cents / 100;
  return new Intl.NumberFormat(locale === 'de' ? 'de-DE' : locale, {
    style: 'currency',
    currency: 'EUR',
  }).format(eur);
}
